// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import type * as outputs from "../types/output";

export interface ConnectionRule {
  deduplicateRule?: outputs.ConnectionRuleDeduplicateRule;
  delayRule?: outputs.ConnectionRuleDelayRule;
  filterRule?: outputs.ConnectionRuleFilterRule;
  retryRule?: outputs.ConnectionRuleRetryRule;
  transformRule?: outputs.ConnectionRuleTransformRule;
}

export interface ConnectionRuleDeduplicateRule {
  /**
   * Fields to exclude when generating deduplicate key
   */
  excludeFields?: string[];
  /**
   * Fields to include when generating deduplicate key
   */
  includeFields?: string[];
  /**
   * Time window in milliseconds to remember deduplication keys when checking for duplicates.
   */
  window: number;
}

export interface ConnectionRuleDelayRule {
  /**
   * Delay to introduce in MS
   */
  delay: number;
}

export interface ConnectionRuleFilterRule {
  body?: outputs.ConnectionRuleFilterRuleBody;
  headers?: outputs.ConnectionRuleFilterRuleHeaders;
  path?: outputs.ConnectionRuleFilterRulePath;
  query?: outputs.ConnectionRuleFilterRuleQuery;
}

export interface ConnectionRuleFilterRuleBody {
  boolean?: boolean;
  /**
   * Stringied JSON using our filter syntax to filter on request headers
   */
  json?: string;
  number?: number;
  string?: string;
}

export interface ConnectionRuleFilterRuleHeaders {
  boolean?: boolean;
  /**
   * Stringied JSON using our filter syntax to filter on request headers
   */
  json?: string;
  number?: number;
  string?: string;
}

export interface ConnectionRuleFilterRulePath {
  boolean?: boolean;
  /**
   * Stringied JSON using our filter syntax to filter on request headers
   */
  json?: string;
  number?: number;
  string?: string;
}

export interface ConnectionRuleFilterRuleQuery {
  boolean?: boolean;
  /**
   * Stringied JSON using our filter syntax to filter on request headers
   */
  json?: string;
  number?: number;
  string?: string;
}

export interface ConnectionRuleRetryRule {
  /**
   * Maximum number of retries to attempt
   */
  count?: number;
  /**
   * Time in MS between each retry
   */
  interval?: number;
  /**
   * HTTP codes to retry on. Accepts: range expressions (e.g., "400-499", ">400"), specific codes (e.g., 404), and exclusions (e.g., "!401"). Example: ["500-599", ">400", 404, "!401"]
   */
  responseStatusCodes?: string[];
  /**
   * must be one of ["linear", "exponential"]
   * Algorithm to use when calculating delay between retries
   */
  strategy: string;
}

export interface ConnectionRuleTransformRule {
  /**
   * ID of the attached transformation object.
   */
  transformationId: string;
}

export interface GetConnectionRule {
  deduplicateRule: outputs.GetConnectionRuleDeduplicateRule;
  delayRule: outputs.GetConnectionRuleDelayRule;
  filterRule: outputs.GetConnectionRuleFilterRule;
  retryRule: outputs.GetConnectionRuleRetryRule;
  transformRule: outputs.GetConnectionRuleTransformRule;
}

export interface GetConnectionRuleDeduplicateRule {
  /**
   * Fields to exclude when generating deduplicate key
   */
  excludeFields: string[];
  /**
   * Fields to include when generating deduplicate key
   */
  includeFields: string[];
  /**
   * Time window in milliseconds to remember deduplication keys when checking for duplicates.
   */
  window: number;
}

export interface GetConnectionRuleDelayRule {
  /**
   * Delay to introduce in MS
   */
  delay: number;
}

export interface GetConnectionRuleFilterRule {
  body: outputs.GetConnectionRuleFilterRuleBody;
  headers: outputs.GetConnectionRuleFilterRuleHeaders;
  path: outputs.GetConnectionRuleFilterRulePath;
  query: outputs.GetConnectionRuleFilterRuleQuery;
}

export interface GetConnectionRuleFilterRuleBody {
  boolean: boolean;
  /**
   * Stringied JSON using our filter syntax to filter on request headers
   */
  json: string;
  number: number;
  string: string;
}

export interface GetConnectionRuleFilterRuleHeaders {
  boolean: boolean;
  /**
   * Stringied JSON using our filter syntax to filter on request headers
   */
  json: string;
  number: number;
  string: string;
}

export interface GetConnectionRuleFilterRulePath {
  boolean: boolean;
  /**
   * Stringied JSON using our filter syntax to filter on request headers
   */
  json: string;
  number: number;
  string: string;
}

export interface GetConnectionRuleFilterRuleQuery {
  boolean: boolean;
  /**
   * Stringied JSON using our filter syntax to filter on request headers
   */
  json: string;
  number: number;
  string: string;
}

export interface GetConnectionRuleRetryRule {
  /**
   * Maximum number of retries to attempt
   */
  count: number;
  /**
   * Time in MS between each retry
   */
  interval: number;
  /**
   * HTTP codes to retry on. Accepts: range expressions (e.g., "400-499", ">400"), specific codes (e.g., 404), and exclusions (e.g., "!401"). Example: ["500-599", ">400", 404, "!401"]
   */
  responseStatusCodes: string[];
  /**
   * must be one of ["linear", "exponential"]
   * Algorithm to use when calculating delay between retries
   */
  strategy: string;
}

export interface GetConnectionRuleTransformRule {
  /**
   * ID of the attached transformation object.
   */
  transformationId: string;
}

export interface WebhookRegistrationRegister {
  request: outputs.WebhookRegistrationRegisterRequest;
  response: string;
}

export interface WebhookRegistrationRegisterRequest {
  body?: string;
  headers?: string;
  method: string;
  url: string;
}

export interface WebhookRegistrationUnregister {
  request: outputs.WebhookRegistrationUnregisterRequest;
}

export interface WebhookRegistrationUnregisterRequest {
  body?: string;
  headers?: string;
  method: string;
  url: string;
}
