export default {
  org: "{{org.name}}",
  archetype: "{{archetype}}",
  projectName: "{{projectName}}",
  domain: "{{domain}}",
  structure: "{{d.structure}}",
  cloudProvider: "{{d.cloudProvider}}",
  iac: "{{d.iac}}",
  runtime: "{{d.runtime}}",
  frontend: "{{d.frontend}}",
  backend: "{{d.backend}}",
  docs: "{{d.docs}}",
  api: "{{d.api}}",
  database: "{{d.database}}",
  databaseHost: "{{d.databaseHost}}",
  databaseRegion: "{{d.databaseRegion}}",
  orm: "{{d.orm}}",
  auth: "{{d.auth}}",
  storage: "{{d.storage}}",
  payments: "{{d.payments}}",
  packageManager: "{{d.packageManager}}",
  git: {{d.git}},
  envs: "{{envs}}",
  trigger: {{trigger}},
  access: {{access}},
  hookdeck: {{hookdeck}},
} as const;
