name: Deploy

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup

      - name: Fetch secrets from Doppler
        uses: ./.github/actions/fetch-secrets
        with:
          env: prd
          project: {{projectName}}
          identity-id: ${{ vars.DOPPLER_IDENTITY_ID }}

      - name: Deploy
        run: bun run deploy
