// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ConnectionArgs, ConnectionState } from "./connection";
export type Connection = import("./connection").Connection;
export const Connection: typeof import("./connection").Connection = null as any;
utilities.lazyLoad(exports, ["Connection"], () => require("./connection"));

export { DestinationArgs, DestinationState } from "./destination";
export type Destination = import("./destination").Destination;
export const Destination: typeof import("./destination").Destination =
  null as any;
utilities.lazyLoad(exports, ["Destination"], () => require("./destination"));

export {
  GetConnectionArgs,
  GetConnectionOutputArgs,
  GetConnectionResult,
} from "./getConnection";
export const getConnection: typeof import("./getConnection").getConnection =
  null as any;
export const getConnectionOutput: typeof import("./getConnection").getConnectionOutput =
  null as any;
utilities.lazyLoad(exports, ["getConnection", "getConnectionOutput"], () =>
  require("./getConnection")
);

export {
  GetDestinationArgs,
  GetDestinationOutputArgs,
  GetDestinationResult,
} from "./getDestination";
export const getDestination: typeof import("./getDestination").getDestination =
  null as any;
export const getDestinationOutput: typeof import("./getDestination").getDestinationOutput =
  null as any;
utilities.lazyLoad(exports, ["getDestination", "getDestinationOutput"], () =>
  require("./getDestination")
);

export {
  GetSourceArgs,
  GetSourceOutputArgs,
  GetSourceResult,
} from "./getSource";
export const getSource: typeof import("./getSource").getSource = null as any;
export const getSourceOutput: typeof import("./getSource").getSourceOutput =
  null as any;
utilities.lazyLoad(exports, ["getSource", "getSourceOutput"], () =>
  require("./getSource")
);

export * from "./provider";

import { Provider } from "./provider";

export { SourceArgs, SourceState } from "./source";
export type Source = import("./source").Source;
export const Source: typeof import("./source").Source = null as any;
utilities.lazyLoad(exports, ["Source"], () => require("./source"));

export { SourceAuthArgs, SourceAuthState } from "./sourceAuth";
export type SourceAuth = import("./sourceAuth").SourceAuth;
export const SourceAuth: typeof import("./sourceAuth").SourceAuth = null as any;
utilities.lazyLoad(exports, ["SourceAuth"], () => require("./sourceAuth"));

export { TransformationArgs, TransformationState } from "./transformation";
export type Transformation = import("./transformation").Transformation;
export const Transformation: typeof import("./transformation").Transformation =
  null as any;
utilities.lazyLoad(exports, ["Transformation"], () =>
  require("./transformation")
);

export {
  WebhookRegistrationArgs,
  WebhookRegistrationState,
} from "./webhookRegistration";
export type WebhookRegistration =
  import("./webhookRegistration").WebhookRegistration;
export const WebhookRegistration: typeof import("./webhookRegistration").WebhookRegistration =
  null as any;
utilities.lazyLoad(exports, ["WebhookRegistration"], () =>
  require("./webhookRegistration")
);

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export { config, types };

const _module = {
  version: utilities.getVersion(),
  construct: (name: string, type: string, urn: string): pulumi.Resource => {
    switch (type) {
      case "hookdeck:index/connection:Connection":
        return new Connection(name, <any>undefined, { urn });
      case "hookdeck:index/destination:Destination":
        return new Destination(name, <any>undefined, { urn });
      case "hookdeck:index/source:Source":
        return new Source(name, <any>undefined, { urn });
      case "hookdeck:index/sourceAuth:SourceAuth":
        return new SourceAuth(name, <any>undefined, { urn });
      case "hookdeck:index/transformation:Transformation":
        return new Transformation(name, <any>undefined, { urn });
      case "hookdeck:index/webhookRegistration:WebhookRegistration":
        return new WebhookRegistration(name, <any>undefined, { urn });
      default:
        throw new Error(`unknown resource type ${type}`);
    }
  },
};
pulumi.runtime.registerResourceModule("hookdeck", "index/connection", _module);
pulumi.runtime.registerResourceModule("hookdeck", "index/destination", _module);
pulumi.runtime.registerResourceModule("hookdeck", "index/source", _module);
pulumi.runtime.registerResourceModule("hookdeck", "index/sourceAuth", _module);
pulumi.runtime.registerResourceModule(
  "hookdeck",
  "index/transformation",
  _module
);
pulumi.runtime.registerResourceModule(
  "hookdeck",
  "index/webhookRegistration",
  _module
);
pulumi.runtime.registerResourcePackage("hookdeck", {
  version: utilities.getVersion(),
  constructProvider: (
    name: string,
    type: string,
    urn: string
  ): pulumi.ProviderResource => {
    if (type !== "pulumi:providers:hookdeck") {
      throw new Error(`unknown provider type ${type}`);
    }
    return new Provider(name, <any>undefined, { urn });
  },
});
