#!/usr/bin/env bun
/**
 * Read every file under `packages/templates/files/` and emit a TypeScript
 * module with the contents baked in as a string-keyed record. Vite bundlers
 * (and the @cloudflare/vite-plugin workerd runner) can't load arbitrary
 * `.json` template files via `import.meta.glob('...', { query: '?raw' })`
 * — the worker loader tries to JSON.parse them before the `?raw` query
 * takes effect. Inlining sidesteps that entirely.
 *
 * Runs in `predev` / `prebuild` so the generated file is always in sync.
 */
import { glob, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = join(SCRIPT_DIR, "..");
const TEMPLATES_DIR = join(SCRIPT_DIR, "../../../packages/templates/files");
const OUT = join(ROOT, "src/lib/generated/templates.ts");

const BINARY_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".ico",
  ".woff",
  ".woff2",
  ".ttf",
  ".eot",
  ".pdf",
  ".zip",
]);

const entries: { path: string; content: string }[] = [];

// glob returns relative-to-cwd paths; use absolute pattern + manual relative.
const pattern = join(TEMPLATES_DIR, "**/*");
for await (const abs of glob(pattern)) {
  const stat = await import("node:fs/promises").then((m) => m.stat(abs));
  if (!stat.isFile()) {
    continue;
  }
  const ext = abs.slice(abs.lastIndexOf(".")).toLowerCase();
  if (BINARY_EXTENSIONS.has(ext)) {
    // Binary files would balloon the bundle; templates that need binary
    // assets (currently none) would have to be handled separately.
    continue;
  }
  const rel = relative(TEMPLATES_DIR, abs);
  const content = await readFile(abs, "utf8");
  entries.push({ path: rel, content });
}

entries.sort((a, b) => a.path.localeCompare(b.path));

const header = `// AUTO-GENERATED by apps/web/scripts/generate-templates.ts — do not edit by hand.
// Run \`bun run generate-templates\` to refresh.

export interface TemplateFile {
  path: string;
  content: string;
}

export const TEMPLATE_FILES: TemplateFile[] = [
`;
const footer = `];

export const TEMPLATE_COUNT = TEMPLATE_FILES.length;
`;

const body = entries
  .map(
    (e) =>
      `  { path: ${JSON.stringify(e.path)}, content: ${JSON.stringify(
        e.content
      )} },`
  )
  .join("\n");

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, `${header}${body}\n${footer}`, "utf8");
console.log(`Wrote ${entries.length} template files → ${OUT}`);
