// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import type * as pulumi from "@pulumi/pulumi";
import type * as inputs from "../types/input";

export interface ConnectionRule {
  deduplicateRule?: pulumi.Input<inputs.ConnectionRuleDeduplicateRule>;
  delayRule?: pulumi.Input<inputs.ConnectionRuleDelayRule>;
  filterRule?: pulumi.Input<inputs.ConnectionRuleFilterRule>;
  retryRule?: pulumi.Input<inputs.ConnectionRuleRetryRule>;
  transformRule?: pulumi.Input<inputs.ConnectionRuleTransformRule>;
}

export interface ConnectionRuleDeduplicateRule {
  /**
   * Fields to exclude when generating deduplicate key
   */
  excludeFields?: pulumi.Input<pulumi.Input<string>[]>;
  /**
   * Fields to include when generating deduplicate key
   */
  includeFields?: pulumi.Input<pulumi.Input<string>[]>;
  /**
   * Time window in milliseconds to remember deduplication keys when checking for duplicates.
   */
  window: pulumi.Input<number>;
}

export interface ConnectionRuleDelayRule {
  /**
   * Delay to introduce in MS
   */
  delay: pulumi.Input<number>;
}

export interface ConnectionRuleFilterRule {
  body?: pulumi.Input<inputs.ConnectionRuleFilterRuleBody>;
  headers?: pulumi.Input<inputs.ConnectionRuleFilterRuleHeaders>;
  path?: pulumi.Input<inputs.ConnectionRuleFilterRulePath>;
  query?: pulumi.Input<inputs.ConnectionRuleFilterRuleQuery>;
}

export interface ConnectionRuleFilterRuleBody {
  boolean?: pulumi.Input<boolean>;
  /**
   * Stringied JSON using our filter syntax to filter on request headers
   */
  json?: pulumi.Input<string>;
  number?: pulumi.Input<number>;
  string?: pulumi.Input<string>;
}

export interface ConnectionRuleFilterRuleHeaders {
  boolean?: pulumi.Input<boolean>;
  /**
   * Stringied JSON using our filter syntax to filter on request headers
   */
  json?: pulumi.Input<string>;
  number?: pulumi.Input<number>;
  string?: pulumi.Input<string>;
}

export interface ConnectionRuleFilterRulePath {
  boolean?: pulumi.Input<boolean>;
  /**
   * Stringied JSON using our filter syntax to filter on request headers
   */
  json?: pulumi.Input<string>;
  number?: pulumi.Input<number>;
  string?: pulumi.Input<string>;
}

export interface ConnectionRuleFilterRuleQuery {
  boolean?: pulumi.Input<boolean>;
  /**
   * Stringied JSON using our filter syntax to filter on request headers
   */
  json?: pulumi.Input<string>;
  number?: pulumi.Input<number>;
  string?: pulumi.Input<string>;
}

export interface ConnectionRuleRetryRule {
  /**
   * Maximum number of retries to attempt
   */
  count?: pulumi.Input<number>;
  /**
   * Time in MS between each retry
   */
  interval?: pulumi.Input<number>;
  /**
   * HTTP codes to retry on. Accepts: range expressions (e.g., "400-499", ">400"), specific codes (e.g., 404), and exclusions (e.g., "!401"). Example: ["500-599", ">400", 404, "!401"]
   */
  responseStatusCodes?: pulumi.Input<pulumi.Input<string>[]>;
  /**
   * must be one of ["linear", "exponential"]
   * Algorithm to use when calculating delay between retries
   */
  strategy: pulumi.Input<string>;
}

export interface ConnectionRuleTransformRule {
  /**
   * ID of the attached transformation object.
   */
  transformationId: pulumi.Input<string>;
}

export interface WebhookRegistrationRegister {
  request: pulumi.Input<inputs.WebhookRegistrationRegisterRequest>;
  response?: pulumi.Input<string>;
}

export interface WebhookRegistrationRegisterRequest {
  body?: pulumi.Input<string>;
  headers?: pulumi.Input<string>;
  method: pulumi.Input<string>;
  url: pulumi.Input<string>;
}

export interface WebhookRegistrationUnregister {
  request: pulumi.Input<inputs.WebhookRegistrationUnregisterRequest>;
}

export interface WebhookRegistrationUnregisterRequest {
  body?: pulumi.Input<string>;
  headers?: pulumi.Input<string>;
  method: pulumi.Input<string>;
  url: pulumi.Input<string>;
}
