// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSource(
  args: GetSourceArgs,
  opts?: pulumi.InvokeOptions
): Promise<GetSourceResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "hookdeck:index/getSource:getSource",
    {
      id: args.id,
    },
    opts,
    utilities.getPackage()
  );
}

/**
 * A collection of arguments for invoking getSource.
 */
export interface GetSourceArgs {
  id: string;
}

/**
 * A collection of values returned by getSource.
 */
export interface GetSourceResult {
  readonly config: string;
  readonly createdAt: string;
  readonly description: string;
  readonly disabledAt: string;
  readonly id: string;
  readonly name: string;
  readonly teamId: string;
  readonly type: string;
  readonly updatedAt: string;
  readonly url: string;
}
export function getSourceOutput(
  args: GetSourceOutputArgs,
  opts?: pulumi.InvokeOutputOptions
): pulumi.Output<GetSourceResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "hookdeck:index/getSource:getSource",
    {
      id: args.id,
    },
    opts,
    utilities.getPackage()
  );
}

/**
 * A collection of arguments for invoking getSource.
 */
export interface GetSourceOutputArgs {
  id: pulumi.Input<string>;
}
