// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Connection extends pulumi.CustomResource {
  /**
   * Get an existing Connection resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: ConnectionState,
    opts?: pulumi.CustomResourceOptions
  ): Connection {
    return new Connection(name, <any>state, { ...opts, id });
  }

  /** @internal */
  public static readonly __pulumiType = "hookdeck:index/connection:Connection";

  /**
   * Returns true if the given object is an instance of Connection.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Connection {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj["__pulumiType"] === Connection.__pulumiType;
  }

  /**
   * Date the connection was created
   */
  public /*out*/ declare readonly createdAt: pulumi.Output<string>;
  /**
   * Description for the connection
   */
  public declare readonly description: pulumi.Output<string | undefined>;
  /**
   * ID of a destination to bind to the connection
   */
  public declare readonly destinationId: pulumi.Output<string>;
  /**
   * Date the connection was disabled
   */
  public declare readonly disabledAt: pulumi.Output<string>;
  /**
   * A unique, human-friendly name for the connection
   */
  public declare readonly name: pulumi.Output<string>;
  /**
   * Date the connection was paused
   */
  public /*out*/ declare readonly pausedAt: pulumi.Output<string>;
  public declare readonly rules: pulumi.Output<
    outputs.ConnectionRule[] | undefined
  >;
  /**
   * ID of a source to bind to the connection
   */
  public declare readonly sourceId: pulumi.Output<string>;
  /**
   * ID of the workspace
   */
  public /*out*/ declare readonly teamId: pulumi.Output<string>;
  /**
   * Date the connection was last updated
   */
  public /*out*/ declare readonly updatedAt: pulumi.Output<string>;

  /**
   * Create a Connection resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(
    name: string,
    args: ConnectionArgs,
    opts?: pulumi.CustomResourceOptions
  );
  constructor(
    name: string,
    argsOrState?: ConnectionArgs | ConnectionState,
    opts?: pulumi.CustomResourceOptions
  ) {
    const resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as ConnectionState | undefined;
      resourceInputs["createdAt"] = state?.createdAt;
      resourceInputs["description"] = state?.description;
      resourceInputs["destinationId"] = state?.destinationId;
      resourceInputs["disabledAt"] = state?.disabledAt;
      resourceInputs["name"] = state?.name;
      resourceInputs["pausedAt"] = state?.pausedAt;
      resourceInputs["rules"] = state?.rules;
      resourceInputs["sourceId"] = state?.sourceId;
      resourceInputs["teamId"] = state?.teamId;
      resourceInputs["updatedAt"] = state?.updatedAt;
    } else {
      const args = argsOrState as ConnectionArgs | undefined;
      if (args?.destinationId === undefined && !opts.urn) {
        throw new Error("Missing required property 'destinationId'");
      }
      if (args?.sourceId === undefined && !opts.urn) {
        throw new Error("Missing required property 'sourceId'");
      }
      resourceInputs["description"] = args?.description;
      resourceInputs["destinationId"] = args?.destinationId;
      resourceInputs["disabledAt"] = args?.disabledAt;
      resourceInputs["name"] = args?.name;
      resourceInputs["rules"] = args?.rules;
      resourceInputs["sourceId"] = args?.sourceId;
      resourceInputs["createdAt"] = undefined /*out*/;
      resourceInputs["pausedAt"] = undefined /*out*/;
      resourceInputs["teamId"] = undefined /*out*/;
      resourceInputs["updatedAt"] = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      Connection.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage()
    );
  }
}

/**
 * Input properties used for looking up and filtering Connection resources.
 */
export interface ConnectionState {
  /**
   * Date the connection was created
   */
  createdAt?: pulumi.Input<string>;
  /**
   * Description for the connection
   */
  description?: pulumi.Input<string>;
  /**
   * ID of a destination to bind to the connection
   */
  destinationId?: pulumi.Input<string>;
  /**
   * Date the connection was disabled
   */
  disabledAt?: pulumi.Input<string>;
  /**
   * A unique, human-friendly name for the connection
   */
  name?: pulumi.Input<string>;
  /**
   * Date the connection was paused
   */
  pausedAt?: pulumi.Input<string>;
  rules?: pulumi.Input<pulumi.Input<inputs.ConnectionRule>[]>;
  /**
   * ID of a source to bind to the connection
   */
  sourceId?: pulumi.Input<string>;
  /**
   * ID of the workspace
   */
  teamId?: pulumi.Input<string>;
  /**
   * Date the connection was last updated
   */
  updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Connection resource.
 */
export interface ConnectionArgs {
  /**
   * Description for the connection
   */
  description?: pulumi.Input<string>;
  /**
   * ID of a destination to bind to the connection
   */
  destinationId: pulumi.Input<string>;
  /**
   * Date the connection was disabled
   */
  disabledAt?: pulumi.Input<string>;
  /**
   * A unique, human-friendly name for the connection
   */
  name?: pulumi.Input<string>;
  rules?: pulumi.Input<pulumi.Input<inputs.ConnectionRule>[]>;
  /**
   * ID of a source to bind to the connection
   */
  sourceId: pulumi.Input<string>;
}
