// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getConnection(
  args: GetConnectionArgs,
  opts?: pulumi.InvokeOptions
): Promise<GetConnectionResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "hookdeck:index/getConnection:getConnection",
    {
      id: args.id,
    },
    opts,
    utilities.getPackage()
  );
}

/**
 * A collection of arguments for invoking getConnection.
 */
export interface GetConnectionArgs {
  id: string;
}

/**
 * A collection of values returned by getConnection.
 */
export interface GetConnectionResult {
  readonly createdAt: string;
  readonly description: string;
  readonly destinationId: string;
  readonly disabledAt: string;
  readonly id: string;
  readonly name: string;
  readonly pausedAt: string;
  readonly rules: outputs.GetConnectionRule[];
  readonly sourceId: string;
  readonly teamId: string;
  readonly updatedAt: string;
}
export function getConnectionOutput(
  args: GetConnectionOutputArgs,
  opts?: pulumi.InvokeOutputOptions
): pulumi.Output<GetConnectionResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "hookdeck:index/getConnection:getConnection",
    {
      id: args.id,
    },
    opts,
    utilities.getPackage()
  );
}

/**
 * A collection of arguments for invoking getConnection.
 */
export interface GetConnectionOutputArgs {
  id: pulumi.Input<string>;
}
