name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup

      - name: Fetch secrets from Doppler
        uses: ./.github/actions/fetch-secrets
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}

      - name: Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: bun run deploy
