// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

declare var exports: any;
const __config = new pulumi.Config("hookdeck");

/**
 * Hookdeck API Base URL. Alternatively, can be configured using the `HOOKDECK_API_BASE` environment variable.
 */
export declare const apiBase: string | undefined;
Object.defineProperty(exports, "apiBase", {
  get() {
    return __config.get("apiBase");
  },
  enumerable: true,
});

/**
 * Hookdeck API Key. Alternatively, can be configured using the `HOOKDECK_API_KEY` environment variable.
 */
export declare const apiKey: string | undefined;
Object.defineProperty(exports, "apiKey", {
  get() {
    return __config.get("apiKey");
  },
  enumerable: true,
});
