// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Destination extends pulumi.CustomResource {
  /**
   * Get an existing Destination resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: DestinationState,
    opts?: pulumi.CustomResourceOptions
  ): Destination {
    return new Destination(name, <any>state, { ...opts, id });
  }

  /** @internal */
  public static readonly __pulumiType =
    "hookdeck:index/destination:Destination";

  /**
   * Returns true if the given object is an instance of Destination.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Destination {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj["__pulumiType"] === Destination.__pulumiType;
  }

  /**
   * Destination configuration
   */
  public declare readonly config: pulumi.Output<string | undefined>;
  /**
   * Date the destination was created
   */
  public /*out*/ declare readonly createdAt: pulumi.Output<string>;
  /**
   * Description for the destination
   */
  public declare readonly description: pulumi.Output<string | undefined>;
  /**
   * Date the destination was disabled
   */
  public declare readonly disabledAt: pulumi.Output<string>;
  /**
   * A unique, human-friendly name for the destination
   */
  public declare readonly name: pulumi.Output<string>;
  /**
   * ID of the workspace
   */
  public /*out*/ declare readonly teamId: pulumi.Output<string>;
  /**
   * Type of the destination
   */
  public declare readonly type: pulumi.Output<string>;
  /**
   * Date the destination was last updated
   */
  public /*out*/ declare readonly updatedAt: pulumi.Output<string>;

  /**
   * Create a Destination resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(
    name: string,
    args?: DestinationArgs,
    opts?: pulumi.CustomResourceOptions
  );
  constructor(
    name: string,
    argsOrState?: DestinationArgs | DestinationState,
    opts?: pulumi.CustomResourceOptions
  ) {
    const resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as DestinationState | undefined;
      resourceInputs["config"] = state?.config;
      resourceInputs["createdAt"] = state?.createdAt;
      resourceInputs["description"] = state?.description;
      resourceInputs["disabledAt"] = state?.disabledAt;
      resourceInputs["name"] = state?.name;
      resourceInputs["teamId"] = state?.teamId;
      resourceInputs["type"] = state?.type;
      resourceInputs["updatedAt"] = state?.updatedAt;
    } else {
      const args = argsOrState as DestinationArgs | undefined;
      resourceInputs["config"] = args?.config
        ? pulumi.secret(args.config)
        : undefined;
      resourceInputs["description"] = args?.description;
      resourceInputs["disabledAt"] = args?.disabledAt;
      resourceInputs["name"] = args?.name;
      resourceInputs["type"] = args?.type;
      resourceInputs["createdAt"] = undefined /*out*/;
      resourceInputs["teamId"] = undefined /*out*/;
      resourceInputs["updatedAt"] = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    const secretOpts = { additionalSecretOutputs: ["config"] };
    opts = pulumi.mergeOptions(opts, secretOpts);
    super(
      Destination.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage()
    );
  }
}

/**
 * Input properties used for looking up and filtering Destination resources.
 */
export interface DestinationState {
  /**
   * Destination configuration
   */
  config?: pulumi.Input<string>;
  /**
   * Date the destination was created
   */
  createdAt?: pulumi.Input<string>;
  /**
   * Description for the destination
   */
  description?: pulumi.Input<string>;
  /**
   * Date the destination was disabled
   */
  disabledAt?: pulumi.Input<string>;
  /**
   * A unique, human-friendly name for the destination
   */
  name?: pulumi.Input<string>;
  /**
   * ID of the workspace
   */
  teamId?: pulumi.Input<string>;
  /**
   * Type of the destination
   */
  type?: pulumi.Input<string>;
  /**
   * Date the destination was last updated
   */
  updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Destination resource.
 */
export interface DestinationArgs {
  /**
   * Destination configuration
   */
  config?: pulumi.Input<string>;
  /**
   * Description for the destination
   */
  description?: pulumi.Input<string>;
  /**
   * Date the destination was disabled
   */
  disabledAt?: pulumi.Input<string>;
  /**
   * A unique, human-friendly name for the destination
   */
  name?: pulumi.Input<string>;
  /**
   * Type of the destination
   */
  type?: pulumi.Input<string>;
}
