// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDestination(
  args: GetDestinationArgs,
  opts?: pulumi.InvokeOptions
): Promise<GetDestinationResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "hookdeck:index/getDestination:getDestination",
    {
      id: args.id,
    },
    opts,
    utilities.getPackage()
  );
}

/**
 * A collection of arguments for invoking getDestination.
 */
export interface GetDestinationArgs {
  id: string;
}

/**
 * A collection of values returned by getDestination.
 */
export interface GetDestinationResult {
  readonly config: string;
  readonly createdAt: string;
  readonly description: string;
  readonly disabledAt: string;
  readonly id: string;
  readonly name: string;
  readonly teamId: string;
  readonly type: string;
  readonly updatedAt: string;
}
export function getDestinationOutput(
  args: GetDestinationOutputArgs,
  opts?: pulumi.InvokeOutputOptions
): pulumi.Output<GetDestinationResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "hookdeck:index/getDestination:getDestination",
    {
      id: args.id,
    },
    opts,
    utilities.getPackage()
  );
}

/**
 * A collection of arguments for invoking getDestination.
 */
export interface GetDestinationOutputArgs {
  id: pulumi.Input<string>;
}
