// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the hookdeck package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
  /** @internal */
  public static readonly __pulumiType = "hookdeck";

  /**
   * Returns true if the given object is an instance of Provider.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Provider {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj["__pulumiType"] === "pulumi:providers:" + Provider.__pulumiType;
  }

  /**
   * Hookdeck API Base URL. Alternatively, can be configured using the `HOOKDECK_API_BASE` environment variable.
   */
  public declare readonly apiBase: pulumi.Output<string | undefined>;
  /**
   * Hookdeck API Key. Alternatively, can be configured using the `HOOKDECK_API_KEY` environment variable.
   */
  public declare readonly apiKey: pulumi.Output<string | undefined>;

  /**
   * Create a Provider resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(
    name: string,
    args?: ProviderArgs,
    opts?: pulumi.ResourceOptions
  ) {
    const resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    resourceInputs["apiBase"] = args?.apiBase;
    resourceInputs["apiKey"] = args?.apiKey
      ? pulumi.secret(args.apiKey)
      : undefined;
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    const secretOpts = { additionalSecretOutputs: ["apiKey"] };
    opts = pulumi.mergeOptions(opts, secretOpts);
    super(
      Provider.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage()
    );
  }

  /**
   * This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
   */
  terraformConfig(): pulumi.Output<{ [key: string]: any }> {
    const result: pulumi.Output<Provider.TerraformConfigResult> =
      pulumi.runtime.call(
        "pulumi:providers:hookdeck/terraformConfig",
        {
          __self__: this,
        },
        this,
        utilities.getPackage()
      );
    return result.result;
  }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
  /**
   * Hookdeck API Base URL. Alternatively, can be configured using the `HOOKDECK_API_BASE` environment variable.
   */
  apiBase?: pulumi.Input<string>;
  /**
   * Hookdeck API Key. Alternatively, can be configured using the `HOOKDECK_API_KEY` environment variable.
   */
  apiKey?: pulumi.Input<string>;
}

export namespace Provider {
  /**
   * The results of the Provider.terraformConfig method.
   */
  export interface TerraformConfigResult {
    readonly result: { [key: string]: any };
  }
}
