// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SourceAuth extends pulumi.CustomResource {
  /**
   * Get an existing SourceAuth resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: SourceAuthState,
    opts?: pulumi.CustomResourceOptions
  ): SourceAuth {
    return new SourceAuth(name, <any>state, { ...opts, id });
  }

  /** @internal */
  public static readonly __pulumiType = "hookdeck:index/sourceAuth:SourceAuth";

  /**
   * Returns true if the given object is an instance of SourceAuth.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is SourceAuth {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj["__pulumiType"] === SourceAuth.__pulumiType;
  }

  /**
   * Source auth
   */
  public declare readonly auth: pulumi.Output<string>;
  /**
   * Type of the source auth
   */
  public declare readonly authType: pulumi.Output<string>;
  /**
   * ID of the source
   */
  public declare readonly sourceId: pulumi.Output<string>;

  /**
   * Create a SourceAuth resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(
    name: string,
    args: SourceAuthArgs,
    opts?: pulumi.CustomResourceOptions
  );
  constructor(
    name: string,
    argsOrState?: SourceAuthArgs | SourceAuthState,
    opts?: pulumi.CustomResourceOptions
  ) {
    const resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as SourceAuthState | undefined;
      resourceInputs["auth"] = state?.auth;
      resourceInputs["authType"] = state?.authType;
      resourceInputs["sourceId"] = state?.sourceId;
    } else {
      const args = argsOrState as SourceAuthArgs | undefined;
      if (args?.auth === undefined && !opts.urn) {
        throw new Error("Missing required property 'auth'");
      }
      if (args?.sourceId === undefined && !opts.urn) {
        throw new Error("Missing required property 'sourceId'");
      }
      resourceInputs["auth"] = args?.auth
        ? pulumi.secret(args.auth)
        : undefined;
      resourceInputs["authType"] = args?.authType;
      resourceInputs["sourceId"] = args?.sourceId;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    const secretOpts = { additionalSecretOutputs: ["auth"] };
    opts = pulumi.mergeOptions(opts, secretOpts);
    super(
      SourceAuth.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage()
    );
  }
}

/**
 * Input properties used for looking up and filtering SourceAuth resources.
 */
export interface SourceAuthState {
  /**
   * Source auth
   */
  auth?: pulumi.Input<string>;
  /**
   * Type of the source auth
   */
  authType?: pulumi.Input<string>;
  /**
   * ID of the source
   */
  sourceId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SourceAuth resource.
 */
export interface SourceAuthArgs {
  /**
   * Source auth
   */
  auth: pulumi.Input<string>;
  /**
   * Type of the source auth
   */
  authType?: pulumi.Input<string>;
  /**
   * ID of the source
   */
  sourceId: pulumi.Input<string>;
}
