// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Transformation extends pulumi.CustomResource {
  /**
   * Get an existing Transformation resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: TransformationState,
    opts?: pulumi.CustomResourceOptions
  ): Transformation {
    return new Transformation(name, <any>state, { ...opts, id });
  }

  /** @internal */
  public static readonly __pulumiType =
    "hookdeck:index/transformation:Transformation";

  /**
   * Returns true if the given object is an instance of Transformation.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Transformation {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj["__pulumiType"] === Transformation.__pulumiType;
  }

  /**
   * JavaScript code to be executed
   */
  public declare readonly code: pulumi.Output<string>;
  /**
   * Date the transformation was created
   */
  public /*out*/ declare readonly createdAt: pulumi.Output<string>;
  /**
   * Key-value environment variables to be passed to the transformation
   */
  public declare readonly env: pulumi.Output<string | undefined>;
  /**
   * A unique, human-friendly name for the transformation
   */
  public declare readonly name: pulumi.Output<string>;
  /**
   * ID of the workspace
   */
  public /*out*/ declare readonly teamId: pulumi.Output<string>;
  /**
   * Date the transformation was last updated
   */
  public /*out*/ declare readonly updatedAt: pulumi.Output<string>;

  /**
   * Create a Transformation resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(
    name: string,
    args: TransformationArgs,
    opts?: pulumi.CustomResourceOptions
  );
  constructor(
    name: string,
    argsOrState?: TransformationArgs | TransformationState,
    opts?: pulumi.CustomResourceOptions
  ) {
    const resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as TransformationState | undefined;
      resourceInputs["code"] = state?.code;
      resourceInputs["createdAt"] = state?.createdAt;
      resourceInputs["env"] = state?.env;
      resourceInputs["name"] = state?.name;
      resourceInputs["teamId"] = state?.teamId;
      resourceInputs["updatedAt"] = state?.updatedAt;
    } else {
      const args = argsOrState as TransformationArgs | undefined;
      if (args?.code === undefined && !opts.urn) {
        throw new Error("Missing required property 'code'");
      }
      resourceInputs["code"] = args?.code;
      resourceInputs["env"] = args?.env ? pulumi.secret(args.env) : undefined;
      resourceInputs["name"] = args?.name;
      resourceInputs["createdAt"] = undefined /*out*/;
      resourceInputs["teamId"] = undefined /*out*/;
      resourceInputs["updatedAt"] = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    const secretOpts = { additionalSecretOutputs: ["env"] };
    opts = pulumi.mergeOptions(opts, secretOpts);
    super(
      Transformation.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage()
    );
  }
}

/**
 * Input properties used for looking up and filtering Transformation resources.
 */
export interface TransformationState {
  /**
   * JavaScript code to be executed
   */
  code?: pulumi.Input<string>;
  /**
   * Date the transformation was created
   */
  createdAt?: pulumi.Input<string>;
  /**
   * Key-value environment variables to be passed to the transformation
   */
  env?: pulumi.Input<string>;
  /**
   * A unique, human-friendly name for the transformation
   */
  name?: pulumi.Input<string>;
  /**
   * ID of the workspace
   */
  teamId?: pulumi.Input<string>;
  /**
   * Date the transformation was last updated
   */
  updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Transformation resource.
 */
export interface TransformationArgs {
  /**
   * JavaScript code to be executed
   */
  code: pulumi.Input<string>;
  /**
   * Key-value environment variables to be passed to the transformation
   */
  env?: pulumi.Input<string>;
  /**
   * A unique, human-friendly name for the transformation
   */
  name?: pulumi.Input<string>;
}
