// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class WebhookRegistration extends pulumi.CustomResource {
  /**
   * Get an existing WebhookRegistration resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: WebhookRegistrationState,
    opts?: pulumi.CustomResourceOptions
  ): WebhookRegistration {
    return new WebhookRegistration(name, <any>state, { ...opts, id });
  }

  /** @internal */
  public static readonly __pulumiType =
    "hookdeck:index/webhookRegistration:WebhookRegistration";

  /**
   * Returns true if the given object is an instance of WebhookRegistration.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is WebhookRegistration {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj["__pulumiType"] === WebhookRegistration.__pulumiType;
  }

  public declare readonly register: pulumi.Output<outputs.WebhookRegistrationRegister>;
  public declare readonly unregister: pulumi.Output<
    outputs.WebhookRegistrationUnregister | undefined
  >;

  /**
   * Create a WebhookRegistration resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(
    name: string,
    args: WebhookRegistrationArgs,
    opts?: pulumi.CustomResourceOptions
  );
  constructor(
    name: string,
    argsOrState?: WebhookRegistrationArgs | WebhookRegistrationState,
    opts?: pulumi.CustomResourceOptions
  ) {
    const resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as WebhookRegistrationState | undefined;
      resourceInputs["register"] = state?.register;
      resourceInputs["unregister"] = state?.unregister;
    } else {
      const args = argsOrState as WebhookRegistrationArgs | undefined;
      if (args?.register === undefined && !opts.urn) {
        throw new Error("Missing required property 'register'");
      }
      resourceInputs["register"] = args?.register;
      resourceInputs["unregister"] = args?.unregister;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      WebhookRegistration.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage()
    );
  }
}

/**
 * Input properties used for looking up and filtering WebhookRegistration resources.
 */
export interface WebhookRegistrationState {
  register?: pulumi.Input<inputs.WebhookRegistrationRegister>;
  unregister?: pulumi.Input<inputs.WebhookRegistrationUnregister>;
}

/**
 * The set of arguments for constructing a WebhookRegistration resource.
 */
export interface WebhookRegistrationArgs {
  register: pulumi.Input<inputs.WebhookRegistrationRegister>;
  unregister?: pulumi.Input<inputs.WebhookRegistrationUnregister>;
}
